#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/hamt_go
  
  
  pySloc -L go cmd/highFindProfileHAMT/highFindProfileHAMT.go cmd/profileHAMT/profileHAMT.go cmd/concurProfileHAMT/concurProfileHAMT.go  -X *.pb.go -v $@
else
  echo "DEV_BASE is not defined"
fi
