#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/hamt_go
  
  pushd cmd/highFindProfileHAMT
  go build && go install
  popd
  pushd cmd/profileHAMT
  go build && go install
  popd
  pushd cmd/concurProfileHAMT
  go build && go install
  popd
  
else
  echo "DEV_BASE is not defined"
fi
